"""empty message

Revision ID: 395625b6d45a
Revises: fc94dd92781e
Create Date: 2023-03-22 15:48:11.110621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '395625b6d45a'
down_revision = 'fc94dd92781e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_products',
    sa.Column('CarId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CarName', sa.String(length=20), nullable=True),
    sa.Column('Supplier', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('CarId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_products')
    # ### end Alembic commands ###
