"""empty message

Revision ID: aa9ddf27651d
Revises: 
Create Date: 2023-03-20 18:40:41.978241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa9ddf27651d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_information',
    sa.Column('ClientId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientName', sa.String(length=30), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Region', sa.String(length=20), nullable=True),
    sa.Column('City', sa.String(length=20), nullable=True),
    sa.Column('District', sa.String(length=20), nullable=True),
    sa.Column('Demand', sa.Text(), nullable=True),
    sa.Column('Delivery', sa.Date(), nullable=True),
    sa.Column('IsUrgentFlag', sa.Enum('1', '0'), nullable=True),
    sa.PrimaryKeyConstraint('ClientId'),
    sa.UniqueConstraint('PhoneNumber')
    )
    op.drop_table('mycustomer')
    op.drop_table('myemployees')
    op.drop_table('conteacher')
    op.drop_table('myowner')
    op.drop_table('recommendlist')
    op.drop_table('purchaseorders')
    op.drop_table('weibo_user')
    op.drop_table('myschool')
    op.drop_table('storelist')
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.drop_index('myorders_pk_customerid')
        batch_op.drop_index('myorders_pk_shipperid')

    op.drop_table('myorders')
    op.drop_table('constudent')
    op.drop_table('myroom')
    op.drop_table('crm_client')
    with op.batch_alter_table('clientinformation', schema=None) as batch_op:
        batch_op.drop_index('PhoneNumber')

    op.drop_table('clientinformation')
    op.drop_table('myproducts')
    op.drop_table('myconposition')
    op.drop_table('mytenant')
    op.drop_table('mycontest_message')
    op.drop_table('areas')
    op.drop_table('mysaleorders')
    op.drop_table('mysuppliers')
    op.drop_table('mycar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mycar',
    sa.Column('carid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('carband', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('carcolor', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('carClass', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('purchasePrice', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('carid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mysuppliers',
    sa.Column('supplierid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('suppliername', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('supplieraddress', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('suppliertel', mysql.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('supplierid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mysaleorders',
    sa.Column('saleid', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('carid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('saletime', sa.DATE(), nullable=True),
    sa.Column('employeeid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('customerid', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('saleid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('areas',
    sa.Column('AreaID', mysql.CHAR(length=10), server_default=sa.text("''"), nullable=False),
    sa.Column('AreaName', mysql.VARCHAR(length=30), server_default=sa.text("''"), nullable=True),
    sa.Column('PYCode', mysql.VARCHAR(length=15), server_default=sa.text("''"), nullable=True),
    sa.Column('Zip', mysql.CHAR(length=10), server_default=sa.text("''"), nullable=True),
    sa.Column('PhoneCode', mysql.CHAR(length=10), server_default=sa.text("''"), nullable=True),
    sa.Column('ParentnodeID', mysql.CHAR(length=10), nullable=True),
    sa.Column('IsparentFlag', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('Ancester', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('level', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('AreaID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mycontest_message',
    sa.Column('testid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('testname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('testhost', mysql.VARCHAR(length=20), nullable=True, comment='主办方'),
    sa.Column('testaddress', mysql.VARCHAR(length=20), nullable=True, comment='举办地址'),
    sa.Column('testtime', sa.DATE(), nullable=True),
    sa.Column('testnote', mysql.TEXT(), nullable=True, comment='比赛安排'),
    sa.PrimaryKeyConstraint('testid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mytenant',
    sa.Column('tenantid', mysql.VARCHAR(length=8), nullable=False, comment='租客编码'),
    sa.Column('tenantname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('tenantroom', mysql.VARCHAR(length=11), nullable=True, comment='租住房间'),
    sa.Column('rentTime', sa.DATE(), nullable=True),
    sa.Column('tenantnumber', mysql.VARCHAR(length=20), nullable=True, comment='租客电话号码'),
    sa.Column('setof', mysql.ENUM('是', '否'), nullable=True, comment='是否缴纳租金'),
    sa.Column('address', mysql.VARCHAR(length=20), nullable=True, comment='房屋地址'),
    sa.PrimaryKeyConstraint('tenantid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myconposition',
    sa.Column('conpositionid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('conposition_kind', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('conposition_mainer', mysql.VARCHAR(length=20), nullable=True, comment='主要负责人'),
    sa.PrimaryKeyConstraint('conpositionid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myproducts',
    sa.Column('ProductID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ProductName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('EnglishName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('QuantityPerunit', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('Unit', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('Unitprice', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('SupplierID', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('CategoryID', mysql.CHAR(length=1), nullable=False),
    sa.Column('SubcategoryID', mysql.CHAR(length=14), nullable=True),
    sa.Column('Photopath', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Discontinued', mysql.BIT(length=1), nullable=True),
    sa.Column('Notes', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('ProductID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('clientinformation',
    sa.Column('ClientId', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('ClientName', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('PhoneNumber', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('RegionId', mysql.VARCHAR(length=20), nullable=True, comment='省'),
    sa.Column('CityId', mysql.VARCHAR(length=20), nullable=True, comment='市'),
    sa.Column('Demand', mysql.MEDIUMTEXT(), nullable=True, comment='需求'),
    sa.Column('Delivery', sa.DATE(), nullable=True),
    sa.Column('IsUrgentFlag', mysql.ENUM('1', '0'), nullable=True),
    sa.PrimaryKeyConstraint('ClientId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('clientinformation', schema=None) as batch_op:
        batch_op.create_index('PhoneNumber', ['PhoneNumber'], unique=False)

    op.create_table('crm_client',
    sa.Column('clientid', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('clientname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('IdNumber', mysql.VARCHAR(length=18), nullable=False),
    sa.Column('birthdate', sa.DATE(), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('job', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('iphone', mysql.CHAR(length=11), nullable=False),
    sa.Column('isVipFlag', mysql.ENUM('是', '否'), nullable=True),
    sa.PrimaryKeyConstraint('clientid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myroom',
    sa.Column('roomid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('roomgrade', mysql.VARCHAR(length=20), nullable=True, comment='房间类型'),
    sa.Column('roomPrice', mysql.DECIMAL(precision=12, scale=2), nullable=True, comment='房间租金'),
    sa.Column('state', mysql.ENUM('是', '否'), nullable=True, comment='是否有人租用'),
    sa.Column('roomaddress', mysql.VARCHAR(length=20), nullable=True, comment='房屋地址'),
    sa.Column('roomarea', mysql.DECIMAL(precision=12, scale=2), nullable=True, comment='房屋面积'),
    sa.PrimaryKeyConstraint('roomid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('constudent',
    sa.Column('studentid', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('studentname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('formschool', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('conposition_id', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('studentid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myorders',
    sa.Column('OrderID', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('OrderDate', sa.DATE(), nullable=True),
    sa.Column('CustomerID', mysql.CHAR(length=14), server_default=sa.text("''"), nullable=True),
    sa.Column('EmployeeID', mysql.CHAR(length=14), server_default=sa.text("''"), nullable=True),
    sa.Column('RequiredDate', sa.DATE(), nullable=True),
    sa.Column('ShippedDate', sa.DATE(), nullable=True),
    sa.Column('InvoiceDate', sa.DATE(), nullable=True),
    sa.Column('ShipperID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Freight', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('Collections', mysql.JSON(), nullable=True),
    sa.Column('Amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('OrderID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('myorders', schema=None) as batch_op:
        batch_op.create_index('myorders_pk_shipperid', ['ShipperID'], unique=False)
        batch_op.create_index('myorders_pk_customerid', ['CustomerID'], unique=False)

    op.create_table('storelist',
    sa.Column('storeid', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('storeimgurl', mysql.VARCHAR(length=100), nullable=True, comment='店家图片地址'),
    sa.Column('storename', mysql.VARCHAR(length=100), nullable=True, comment='店名'),
    sa.Column('chattime', sa.DATE(), nullable=True, comment='上次聊天时间'),
    sa.PrimaryKeyConstraint('storeid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myschool',
    sa.Column('schoolid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('schoolname', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('schoolid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('weibo_user',
    sa.Column('userid', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('userpassword', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('userGender', mysql.ENUM('男', '女'), nullable=True),
    sa.Column('iphoneNumber', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('purchaseorders',
    sa.Column('orderid', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('carid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('orderid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recommendlist',
    sa.Column('productid', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('producturl', mysql.VARCHAR(length=100), nullable=True, comment='商品地址'),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=True, comment='价格'),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='购买数量'),
    sa.Column('productText', mysql.TEXT(), nullable=True, comment='商品描述'),
    sa.PrimaryKeyConstraint('productid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myowner',
    sa.Column('ownerid', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ownername', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('ownerRoom_id', mysql.VARCHAR(length=20), nullable=True, comment='房东的房子id'),
    sa.Column('ownerCard_id', mysql.VARCHAR(length=20), nullable=True, comment='房东身份证号'),
    sa.Column('ownerTel', mysql.VARCHAR(length=20), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('conteacher',
    sa.Column('teacherid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('teachername', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('fromschool', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('conposition_id', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('teacherid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('myemployees',
    sa.Column('RowID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('EmployeeID', mysql.CHAR(length=7), nullable=True),
    sa.Column('Employeename', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=30), nullable=True),
    sa.Column('Gender', mysql.CHAR(length=2), nullable=True),
    sa.Column('Birthdate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('RowID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mycustomer',
    sa.Column('customerid', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('customername', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('customeraddress', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('customertel', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('customerid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('order_information')
    # ### end Alembic commands ###
