"""empty message

Revision ID: fc94dd92781e
Revises: aa9ddf27651d
Create Date: 2023-03-20 18:41:34.026307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc94dd92781e'
down_revision = 'aa9ddf27651d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_information',
    sa.Column('ClientId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ClientName', sa.String(length=30), nullable=True),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=True),
    sa.Column('Address', sa.String(length=100), nullable=True),
    sa.Column('Region', sa.String(length=20), nullable=True),
    sa.Column('City', sa.String(length=20), nullable=True),
    sa.Column('District', sa.String(length=20), nullable=True),
    sa.Column('Demand', sa.Text(), nullable=True),
    sa.Column('Delivery', sa.Date(), nullable=True),
    sa.Column('IsUrgentFlag', sa.Enum('1', '0'), nullable=True),
    sa.PrimaryKeyConstraint('ClientId'),
    sa.UniqueConstraint('PhoneNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_information')
    # ### end Alembic commands ###
